name: cohort360-front-run-tests

on: [push]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run test
      - name: Lint
        run: npm run lint
